<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.pushi.gv.pom</groupId>
        <artifactId>gv-pom</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath/>
    </parent>
    <artifactId>gv-base</artifactId>
    <packaging>pom</packaging>

    <name>gv-base</name>
    <description>图可视化基础模块</description>

    <modules>
        <module>gv-entity</module>
        <module>gv-common</module>
        <module>gv-exception</module>
        <module>gv-config</module>
    </modules>
</project>